# Generated by Django 5.2.8 on 2026-02-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
